### ISSUE TITLE
modtype-umm does not have validationCode

### ISSUE THREAD

**Issue by m3t4f1v3** [NicBOMB/Vortex#1]
**Describe the bug**
during `pnpm install`, the install errors out at modtype-umm, citing `Module not found: Error: Can't resolve './validationCode/validation' in '/home/edward_wong/.cache/paru/clone/Vortex/extensions/modtype-umm/src'`

 - OS: Artix Linux

Attempting to copy the src/validationCode directory there also yields no results as validateIUMMGameConfig is not found in it

**Comment by palexdev** [comment]
I'm having this issue too

**Comment by palexdev** [comment]
I bypassed this error by removing the import and the verification code related to it in the `index.ts` file
It now compiles, but I'm having a pletora of other errors
At this point screw this project, it's easier to install it via Lutris

**Comment by palexdev** [comment]
Ah so this is uncomplete
Sorry, I thought it was at least compilable

Looking forward for a release!
